config/routes.rb
Rails.application.routes.draw do
	resources :surveys, except: [:new, :create] do
		collection do
			get :intro
		end
		member do
			get :defining
			get :differentiation
			get :thanks
		end
	end

	root to: 'visitors#index'
	devise_for :users, skip: :registerable
	get 'admin', to: 'visitors#admin', as: :admin
end

app/models/survey.rb
class Survey < ActiveRecord::Base

	acts_as_taggable

	validates :step, presence: true
	#validates :area_of_expertise, presence: true
	#validates :definition, :papers, presence: true, if: 'step>1'
	#validates :big_data_vs_data_science, :machine_learning_vs_data_science, :stat_vs_data_science, presence: true, if: 'step>2'
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, if: "email&&email!=''"
	validates :access_token, uniqueness: {case_sensitive: false}, presence: true
	ABOUT_YOU = 1
	DEFINING = 2
	DIFFERENTIATION = 3
	STEPS = {ABOUT_YOU => 'About You', DEFINING => 'Definition', DIFFERENTIATION => 'Differentiation'}
	validates :step, inclusion: { in: STEPS.keys }
	serialize :associated_areas, Array
	ASSOCIATED_AREAS = {
		1 => 'Predictive Analytics',
		2 => 'Visualization',
		3 => 'Deriving knowledge from data',
		4 => 'Artificial Intelligence',
		5 => 'Machine Learning',
		6 => 'Data Engineering',
		7 => 'Pattern Recognition',
		8 => 'Data Warehousing',
		9 => 'Big Data',
		10 => 'Probability Models',
		11 => 'Signal Processing',
		12 => 'Science',
		13 => 'Statistics',
		14 => 'Uncertainty Study',
		15 => 'Modeling',
		16 => 'Automation',
		17 => 'Curation',
		18 => 'Medical Data Mining',
		19 => 'Educational Data Mining'
	}

	DEGREE_LEVELS = {1 => 'Ph.D', 2 => 'M.S.', 3 => 'B.S.', 4 => 'Other'}
	PROFESSIONS = {1 => 'Academic', 2 => 'Industry', 3 => 'Other'}
	DISCIPLINES = {1 => 'Computer Science', 2 => 'Electrical', 3 => 'Mechanical',
		4 => 'Physics', 5 => 'Arts', 6 => 'Chemistry', 7 => 'Other'}
	EXPERIENCE_LEVELS = {1 => '1-5 Years', 2 => '5-10 Years', 3 => '10-15 Years', 4 => '>15 Years'}

	before_validation :set_fields

	def clean_associated_areas
		(self.associated_areas||[]).compact.collect{|aa| aa.to_i} rescue []
	end

	def associated_areas_name
		self.associated_areas_list.join(', ')
	end

	def associated_areas_list
		self.clean_associated_areas.collect{|aa| ASSOCIATED_AREAS[aa]}.compact
	end

	def degree_level_name
		DEGREE_LEVELS[self.degree_level]
	end

	def profession_name
		PROFESSIONS[self.profession]
	end

	def discipline_name
		DISCIPLINES[self.discipline]
	end

	def experience_level_name
		EXPERIENCE_LEVELS[self.experience_level]
	end

	def step_name
		STEPS[self.step]
	end

	def full_name
		"#{self.name}#{" (#{self.email})" if self.email.present?}"
	end

	def self.remove_empty_rows
		Survey.all.each do |survey|
			if survey.definition.blank? && survey.associated_areas.blank? && survey.degree_level.blank? && survey.big_data_vs_data_science.blank? && survey.machine_learning_vs_data_science.blank? && survey.stat_vs_data_science.blank? && survey.all_curation_tech.blank? && survey.all_crution_explain.blank? && survey.profession.blank? && survey.discipline.blank? && survey.experience_level.blank? #&& survey.access_token.blank? && survey.step.blank?
				survey.destroy
			end
		end
	end

	private
	def set_fields
		self.access_token||=Digest::MD5.hexdigest("#{self.name}-#{Time.now.to_i}")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_taggable
  enum role: [:user, :admin]
  after_initialize :set_default_role, if: :new_record?
  def set_default_role
    self.role ||= :user
  end
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin_only
    access_denied unless current_user && current_user.admin?
  end

  def access_denied
    redirect_to root_path, alert: "Access denied."
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :authenticate_user!, only: [:destroy, :index, :show]
  before_filter :admin_only, only: [:destroy, :index, :show]
  before_action :set_survey, only: [:edit, :update, :destroy, :defining,
                                    :differentiation, :thanks]

  def index
    @surveys = initialize_grid(Survey)
  end

  def show
    @survey = Survey.find_by_id(params[:id]) if current_user && current_user.admin?
    redirect_to root_path, alert: 'Survey not found' if @survey.blank?
  end

  def intro
    @survey = (session[:access_token_datascience].blank?) ? Survey.new : Survey.find_by_access_token(session[:access_token_datascience])
    @survey.save
    session[:access_token_datascience] = @survey.access_token if session[:access_token_datascience].blank?
  end

  def edit
  end

  def update
    if @survey.update(survey_params)
      session.delete(:access_token_datascience)
      redirect_to_page(@survey)
    else
      actions = {Survey::ABOUT_YOU => :new, Survey::DEFINING => :defining, Survey::DIFFERENTIATION => :differentiation}
      render action: actions[@survey.step]
    end
  end

  def destroy
    @survey.destroy
    redirect_to surveys_path
  end

  def defining
  end

  def differentiation
  end

  def thanks
  end

  private

    def set_survey
      @survey = Survey.find_by_access_token(session[:access_token_datascience]) || Survey.find_by_access_token(params[:id]) || ((current_user && current_user.admin?) && Survey.find_by_id(params[:id]))
      redirect_to root_path, alert: 'Survey not found' if @survey.blank?
    end

    def survey_params
      params.require(:survey).permit(:definition, {associated_areas: []}, :papers,
        :area_of_expertise, :name, :email, :degree_level, :big_data_vs_data_science,
        :machine_learning_vs_data_science, :stat_vs_data_science, :all_curation_tech,
        :all_crution_explain, :step, :profession, :discipline, :experience_level, :ok_storing_details, :tag_list)
    end

    def redirect_to_page(survey)
      redirect_page = {Survey::ABOUT_YOU => defining_survey_path(id: survey.access_token),
        Survey::DEFINING => differentiation_survey_path(id: survey.access_token),
        Survey::DIFFERENTIATION => thanks_survey_path(id: survey.access_token)}
      redirect_to redirect_page[survey.step]
    end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	before_filter :authenticate_user!, only: [:admin]
	before_filter :admin_only, only: [:admin]

	def admin
		redirect_to surveys_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
	def associated_list(list)
		content_tag(:p, raw(list.collect{|associated_area| associated_area_tag(associated_area)}.join(' ')), class: 'associated-areas')
	end

	def associated_area_tag(associated_area)
		content_tag(:span, raw("#{content_tag(:i, '', class: "fa fa-check-circle")} #{associated_area}"), class: 'label label-success')
	end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
	<li><%= link_to 'Surveys', surveys_path %></li>
	<li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Data Science Survery" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Data Science Survery" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' if user_signed_in? %>
    </header>
    <main role="main" class="<%= 'admin' if user_signed_in? %>">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/surveys/_steps.html.erb
<div class="steps row">
	<div class="col-md-3<%= ' active' if step == 0 %>">
		<div class="step red">
			<h3><%= link_to("Introduction", intro_surveys_path) %></h3>
		</div>
	</div>
	<div class="col-md-3<%= ' active' if step == 1 %>">
		<div class="step blue">
			<h3><%= link_to("About You", edit_survey_path(id: @survey.access_token)) %></h3>
		</div>
	</div>
	<div class="col-md-3<%= ' active' if step == 2 %>">
		<div class="step brown">
			<h3><%= link_to("Definition", defining_survey_path(id: @survey.access_token) ) %></h3>
		</div>
	</div>
	<div class="col-md-3<%= ' active' if step == 3 %>">
		<div class="step purple">
			<h3><%= link_to("Differentiation", differentiation_survey_path(id: @survey.access_token) ) %></h3>
		</div>
	</div>
</div>
<div class="bottom-steps row">
	<div class="col-md-3 red"></div>
	<div class="col-md-3 blue"></div>
	<div class="col-md-3 brown"></div>
	<div class="col-md-3 purple"></div>
</div>

app/views/surveys/defining.html.erb
<div class="public-container container">
  <%= render partial: 'steps', locals: {step: 2} %>
  <h1 class="text-center">Defining Data Science</h1>
  <%= simple_form_for(@survey, url: survey_path(id: @survey.access_token)) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :step, value: Survey::DEFINING %>
  <div class="form-inputs">
    <%= f.input :definition, label: 'Your definition of data science' %>
    <p><strong>What amongst these you most associate with data science?</strong></p>
    <% associated_areas = f.object.clean_associated_areas %>
    <% Survey::ASSOCIATED_AREAS.collect do |id, name| %>
    <label class="switch">
      <%= f.check_box :associated_areas, {multiple: true, checked: associated_areas.include?(id)}, id, nil %>
      <span><i class="fa fa-times-circle"></i> <%= name %></span>
    </label>
    <% end %>

    <p></p>

    <p><strong>More Associations with Data Science (Keep associations comma (,) separated)</strong></p>
    <ul id="tags">
      <% unless f.object.tag_list.blank? %>
      <% f.object.tag_list.each do |tag| %>
      <li><%= tag %></li>
      <% end %>
      <% end %>
    </ul>

    <p></p>
    <% if user_signed_in? %>
      <div class="form-group">
        <%= f.label 'Tags'%>
        <div class="row">
          <div class="col-md-6">
            <ul id="tags">
            <% unless current_user.tag_list.blank? %>
              <% current_user.tag_list.each do |tag| %>
              <li><%= tag %></li>
              <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    <%= f.input :papers, label: 'Research papers, articles, blogs that are great resources for data science' %>
  </div>
  <div class="form-actions pull-right next-btn">
    <%= f.button :submit, value: 'Save & Next >', class: 'btn btn-primary btn-lg' %>
  </div>
  <% end %>
</div>

app/views/surveys/differentiation.html.erb
<div class="public-container container">
  <%= render partial: 'steps', locals: {step: 3} %>
  <h1 class="text-center">Differentiating Data Science</h1>
  <p><strong>In your own words, please help us differentiate between the following:</strong></p>
  <%= simple_form_for(@survey, url: survey_path(id: @survey.access_token)) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :step, value: Survey::DIFFERENTIATION %>
  <div class="form-inputs">
    <%= f.input :big_data_vs_data_science, label: 'Big Data technologies vs. Data Science (Big data technologies: Hadoop, spark etc.) ' %>
    <%= f.input :machine_learning_vs_data_science, label: 'Machine learning vs. Data Science (Machine learning: supervised learning, clustering, classification, deep learning, graphical models)' %>
    <%= f.input :stat_vs_data_science, label: 'Statistics vs. Data Science (Statistics: bootstrap methods, cross validation, time series analysis etc.)' %>
    <div class="form-group">
      <%= f.label 'Would you say  Data Science transcends Machine learning, Big Data technologies and Statistics, Information visualization technologies, Curation technologies?' %><br />
      <div class="btn-group radio-btn-group" data-toggle="buttons">
        <%= f.label :name, class: "btn btn-default#{' active' if f.object.all_curation_tech}" do %>
        <%= f.radio_button :all_curation_tech, true, onchange: "$('#all_crution_explain').fadeIn();" %> Yes
        <% end %>
        <%= f.label :name, class: "btn btn-default#{' active' if f.object.all_curation_tech == false}" do %>
        <%= f.radio_button :all_curation_tech, false, onchange: "$('#all_crution_explain').fadeOut();" %> No
        <% end %>
      </div>
    </div>
    <%= f.input :all_crution_explain, label: 'Please Explain', wrapper_html: {style: f.object.all_curation_tech ? nil : 'display:none;', id: 'all_crution_explain'} %>
  </div>
  <div class="form-actions pull-right next-btn">
    <%= f.button :submit, value: 'Finish', class: 'btn btn-primary btn-lg' %>
  </div>
  <% end %>
</div>

app/views/surveys/edit.html.erb
<div class="public-container container">
	<%= render partial: 'steps', locals: {step: 1} %>
	<h1 class="text-center">About You</h1>
	<%= simple_form_for(@survey, html: { onSubmit: "return checkForm(this);"}) do |f| %>
	<%= f.error_notification %>
	<%= f.hidden_field :step, value: Survey::ABOUT_YOU %>
	<div class="form-inputs">
		<div class="form-group">
			<%= f.label 'Highest Degree Level / Profession' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::DEGREE_LEVELS.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.degree_level == id}" do %>
				<%= f.radio_button :degree_level, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label 'Academic or Business' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::PROFESSIONS.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.profession == id}" do %>
				<%= f.radio_button :profession, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<%= f.input :area_of_expertise, label: 'Area of Experties / Research Interests' %>
		<div class="form-group">
			<%= f.label 'Discipline' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::DISCIPLINES.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.discipline == id}" do %>
				<%= f.radio_button :discipline, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label 'Experience Level' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::EXPERIENCE_LEVELS.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.experience_level == id}" do %>
				<%= f.radio_button :experience_level, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<%= f.input :name, label: "Name (Optional)" %>
		<%= f.input :email, label: "Email (Optional)" %>

		<div class="form-group">
      <%= f.label 'It is NOT necessary for you to give your Name and Email above, but in case you did, please confirm that you are OK with having this information stored?' %><br />
      <div class="btn-group radio-btn-group" data-toggle="buttons">
        <%= f.label :name, class: "btn btn-default#{' active' if f.object.ok_storing_details}" do %>
        <%= f.radio_button :ok_storing_details, true, onchange: "$('#all_crution_explain').fadeIn();" %> Yes
        <% end %>
        <%= f.label :name, class: "btn btn-default#{' active' if f.object.ok_storing_details == false}" do %>
        <%= f.radio_button :ok_storing_details, false, onchange: "$('#all_crution_explain').fadeOut();" %> No
        <% end %>
      </div>
    </div>

	</div>
	<div class="form-actions pull-right next-btn">
		<%= f.button :submit, value: 'Save & Next >', class: 'btn btn-primary btn-lg', id: "survey_next" %>
	</div>
	<% end %>
	<div id="dialog-confirm"></div>
</div>

app/views/surveys/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Surveys</h2></div>
  <div class="panel-body">
<%= grid(@surveys) do |g|

  g.column name: 'Name (Email)', attribute: 'name' do |survey|
    survey.full_name
  end

  g.column name: 'Access Token', attribute: 'access_token' do |survey|
    survey.access_token
  end

  g.column name: 'Degree Level', attribute: 'degree_level', custom_filter: Survey::DEGREE_LEVELS.collect{|id, name| [name, id]} do |survey|
    survey.degree_level_name
  end

  g.column name: 'Academic or business', attribute: 'profession', custom_filter: Survey::PROFESSIONS.collect{|id, name| [name, id]} do |survey|
    survey.profession_name
  end

  g.column name: 'Discipline', attribute: 'discipline', custom_filter: Survey::DISCIPLINES.collect{|id, name| [name, id]} do |survey|
    survey.discipline_name
  end

  g.column name: 'Experience Level', attribute: 'experience_level', custom_filter: Survey::EXPERIENCE_LEVELS.collect{|id, name| [name, id]} do |survey|
    survey.experience_level_name
  end

  g.column name: 'Actions' do |survey|
    raw("#{link_to 'View', survey, class: 'btn btn-primary btn-xs'}
    #{link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-info btn-xs'}")
  end
end %>
</div>
</div>

app/views/surveys/intro.html.erb
<div class="public-container container introduction">
	<%= render partial: 'steps', locals: {step: 0} %>
	<h1 class="text-center">Introduction</h1>
	<p>Through this survey we are asking how do you define Data Science? Many articles tout its significance, and one can read about them <%= link_to 'here', "https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century/", target: "_blank" %>, <%= link_to 'here', "http://en.wikipedia.org/wiki/Data_science", target: "_blank" %> and <%= link_to 'here', "http://harvardmagazine.com/2014/03/why-big-data-is-a-big-deal", target: "_blank" %>. It is a field that is emerging by merging multiple otherwise independent fields. It has driven many academic institutions to start academic programs <%= link_to "Berkeley Data science program", "http://datascience.berkeley.edu/academics/curriculum/", target: "_blank" %>, Institutes and centers (For example: <%= link_to "@Columbia","http://datascience.columbia.edu/", target: "_blank" %>, <%= link_to "@NYU", "http://datascience.nyu.edu/", target: "_blank" %>). United states has created a position and appointed a Chief data scientist.</p>

	<p>Yet there is criticism as to what defines/constitutes Data Science? In general, there seems to be a consensus that Data Science is use of several methods and technologies to generate knowledge/insights/ from data (see the wikipedia description <%= link_to 'here', "http://en.wikipedia.org/wiki/Data_science", target: "_blank" %>). These insights help us understand a complex system and could aid in decision making. However, there seems to be a question of what exactly is new and challenging? For example, on Wikipedia there is criticism about Data Science and we quote:</p>

	<blockquote>
		Although use of the term "data science" has exploded in business environments, many academics and journalists see no distinction between data science and statistics. Writing in Forbes, Gil Press argues that data science is a buzzword without a clear definition and has simply replaced "business analytics" in contexts such as graduate degree programs. In the question-and-answer section of his keynote address at the Joint Statistical Meetings of American Statistical Association, noted applied statistician Nate Silver said, "I think data-scientist is a sexed up term for a statistician....Statistics is a branch of science. Data scientist is slightly redundant in some way and people shouldn’t berate the term statistician.
	</blockquote>

	<p>
		But within the criticisms and its exponential growth, there are some questions that could deliver answers to some very pragmatic needs which are: What skills are necessary in a data scientist? What would a Data Science curriculum look like? Should we, in an ad hoc fashion, piece together multiple well defined technologies/fields like Machine learning, Big Data, and Statistics, Visualization to define a data science curriculum, or is there a different way to look at it?
	</p>

	<h3>Who are we?</h3>
	<p>We are a data science group called Any Scale Learning For All, <%= link_to 'ALFA', "http://groups.csail.mit.edu/EVO-DesignOpt/groupWebSite/", target: "_blank" %> at <%= link_to 'CSAIL', "http://www.csail.mit.edu/", target: "_blank" %>, <%= link_to 'MIT', "http://web.mit.edu/", target: "_blank" %>. This survey is also co-sponsored by <%= link_to "BigData@CSAIL", "http://bigdata.csail.mit.edu/", target: "_blank" %>. Please contact <%= link_to "Kalyan Veeramachaneni", "http://www.kalyanv.org/", target: "_blank" %> at <%= mail_to "kalyan@csail.mit.edu", "kalyan@csail.mit.edu" %> if you have any questions. 
	</p>

	<div class="text-center pull-right next-btn">
		<%= link_to 'Next >', edit_survey_path(id: @survey.access_token), class: 'btn btn-primary btn-lg' %>
	</div>
</div>

app/views/surveys/new.html.erb
<div class="public-container container">
	<%= render partial: 'steps', locals: {step: 1} %>
	<h1 class="text-center">About You</h1>
	<%= simple_form_for(@survey, html: { onSubmit: "return checkForm(this);"}) do |f| %>
	<%= f.error_notification %>
	<%= f.hidden_field :step, value: Survey::ABOUT_YOU %>
	<div class="form-inputs">
		<div class="form-group">
			<%= f.label 'Highest Degree Level / Profession' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::DEGREE_LEVELS.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.degree_level == id}" do %>
				<%= f.radio_button :degree_level, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label 'Academic or Business' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::PROFESSIONS.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.profession == id}" do %>
				<%= f.radio_button :profession, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<%= f.input :area_of_expertise, label: 'Area of Experties / Research Interests' %>
		<div class="form-group">
			<%= f.label 'Discipline' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::DISCIPLINES.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.discipline == id}" do %>
				<%= f.radio_button :discipline, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label 'Experience Level' %><br />
			<div class="btn-group radio-btn-group" data-toggle="buttons">
				<% Survey::EXPERIENCE_LEVELS.collect do |id, name| %>
				<%= f.label :name, class: "btn btn-default#{' active' if f.object.experience_level == id}" do %>
				<%= f.radio_button :experience_level, id %> <%= name %>
				<% end %>
				<% end %>
			</div>
		</div>
		<%= f.input :name, label: "Name (Optional)" %>
		<%= f.input :email, label: "Email (Optional)" %>
	</div>
	<div class="form-actions pull-right next-btn">
		<%= f.button :submit, value: 'Next >', class: 'btn btn-primary btn-lg', id: "survey_next" %>
	</div>
	<% end %>
	<div id="dialog-confirm"></div>
</div>

<script type="text/javascript">
	function checkForm(f)
	{
		if ($('#survey_name').val() != '' || $('#survey_email').val() != '')
		{
			 $("#dialog-confirm").dialog('open');
			return false;
		}
		else
		{
			f.submit();
			return false;
		}
		$("#dialog-confirm").dialog({
	        resizable: false,
	        modal: true,
	        title: "Confirmation!",
	        height: 250,
	        width: 400,
	        buttons: {
	            "Yes": function () {
	                $(this).dialog('close');
	                //callback(true);
	                submit = true
	            },
	                "No": function () {
	                $(this).dialog('close');
	                //callback(false);
	            }
	        }
	    });
	}
</script>

app/views/surveys/thanks.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="text-center">
					<h1>Thanks</h1>
					<p>Thanks for your feedback</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/visitors/admin.html.erb
<h1>Admin Panel</h1>

app/views/visitors/index.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body text-center">
				<h1>Help us position Data Science</h1>
				<%= link_to 'Start Survey', intro_surveys_path, class: 'btn btn-primary btn-lg' %>
			</div>
		</div>
	</div>
</div>